/**
 * @file KYC.ts
 * @description Types and interfaces for KYC (Know Your Customer) records, logs, and upload responses.
 */

import type { OnChainInfo } from './Info';

/**
 * Allowed KYC statuses.
 */
export type KYCStatus = 'Draft' | 'Reviewed' | 'Signed' | 'Revoked';

/**
 * Represents a KYC document or record.
 */
export interface KYC {
  /** Unique identifier for the KYC token. */
  tokenId: string;

  /** Owner wallet address. */
  owner: string;

  /** IPFS or file hash of the KYC document. */
  fileHash: string;

  /** URL to metadata JSON. */
  metadataUrl: string;

  /** Optional URL to the document. */
  documentUrl?: string;

  /** Optional KYC name/title. */
  name?: string;

  /** Optional description of the KYC. */
  description?: string;

  /** Optional blockchain transaction hash. */
  txHash?: string;

  /** Creation timestamp (Unix ms). */
  createdAt: number;

  /** Last update timestamp (Unix ms). */
  updatedAt?: number;

  /** Current status of the KYC. */
  status: KYCStatus;

  // --- Internal processing fields ---
  /** Address of the reviewer. */
  reviewedBy?: string;

  /** Signature of approval. */
  signature?: string;

  /** Internal remarks or notes. */
  remarks?: string;
}

/**
 * Log entry for KYC actions.
 * @template TExtra - type of optional extra metadata (default: Record<string, unknown>)
 */
export interface KYCLogEntry<TExtra = Record<string, unknown>> {
  /** Action performed. */
  action: 'mintKYC' | 'reviewKYC' | 'signKYC' | 'revokeKYC' | 'deleteKYC' | 'internal_update';

  /** Transaction hash associated with this action. */
  txHash: string;

  /** Account that performed the action. */
  account: string;

  /** Optional executor account. */
  executor?: string;

  /** Optional additional metadata. */
  extra?: TExtra;

  /** Timestamp of the action (Unix ms). */
  timestamp: number;

  /** Optional on-chain information. */
  onChainInfo?: OnChainInfo;

  /** Optional detailed info about the action. */
  details?: {
    status?: string;
    reviewedBy?: string;
    signature?: string;
  };
}

/**
 * KYC logs container.
 * @template TExtra - type of optional extra metadata in logs.
 */
export interface KYCLogs<TExtra = Record<string, unknown>> {
  /** Token ID associated with the logs. */
  tokenId: number;

  /** History of all log entries. */
  history: KYCLogEntry<TExtra>[];
}

/**
 * Response structure returned by the KYC upload API (e.g., trade-chain or FastAPI service).
 */
export interface KYCUploadResponse {
  /** Unique KYC token ID generated by the external service. */
  tokenId: string;

  /** Optional URL pointing to the uploaded KYC document. */
  documentUrl?: string;

  /** Optional current status returned from the upload process. */
  status?: KYCStatus;

  /** Optional IPFS or storage hash of the uploaded file. */
  fileHash?: string;

  /** Optional message or description returned from the service. */
  message?: string;

  /** Any additional fields returned by the external API. */
  [key: string]: unknown;
}
